Blog.Admin/Controllers/GaleryController.cs
using Blog.Model;
using Blog.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Admin.Controllers
{
    public class GaleryController : ControllerBase
    {
        // GET: Galery
        private readonly IGaleryService galeryService;
        private readonly ICategoryService categoryService;
        public GaleryController(IGaleryService galeryService,ICategoryService categoryService) :base()
        {
            this.galeryService = galeryService;
            this.categoryService = categoryService;

        }
        // GET: Category
        public ActionResult Index()
        {
            var galeries = galeryService.GetAll();
            ViewBag.Categories = categoryService.GetAll();
            return View(galeries);
        }
        public ActionResult Create()
        {
            var galery = new Galery();
            return View(galery);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Galery galery, HttpPostedFileBase[] Uploads)
        {
            if (ModelState.IsValid)
            {
                if (Uploads != null && Uploads.Length >= 1)
                {
                    galery.GaleryFiles.Clear();
                    foreach (var item in Uploads)
                    {
                        if (item != null && item.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(item.FileName);
                            var extension = Path.GetExtension(fileName).ToLower();
                            if (extension == ".jpg" || extension == ".gif" || extension == ".png" || extension == ".pdf" || extension == ".doc" || extension == ".docx")
                            {
                                var path = Path.Combine(ConfigurationManager.AppSettings["uploadPath"], fileName);
                                item.SaveAs(path);
                                var file = new GaleryFile();
                                file.Id = Guid.NewGuid();
                                file.FileName = fileName;
                                file.CreatedAt = DateTime.Now;
                                file.CreatedBy = User.Identity.Name;
                                file.UpdatedAt = DateTime.Now;
                                file.UpdatedBy = User.Identity.Name;

                                galery.GaleryFiles.Add(file);
                            }
                        }
                    }
                }
                galeryService.Insert(galery);
                return RedirectToAction("Index");
            }

        
            
            return View(galery);
        }
        public ActionResult Edit(Guid id)
        {

            var galery = galeryService.Find(id);
            if (galery == null)
            {
                return HttpNotFound();

            }
            return View(galery);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Galery galery, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(upload.FileName);
                    string extension = Path.GetExtension(fileName).ToLower();
                    if (extension == ".jpg" || extension == ".jpeg" || extension == ".png" || extension == ".gif")
                    {
                        string path = Path.Combine(ConfigurationManager.AppSettings["uploadPath"], fileName);
                        upload.SaveAs(path);
                        galery.Photo = fileName;
                        galeryService.Update(galery);
                        return RedirectToAction("index");
                    }
                    else
                    {
                        ModelState.AddModelError("Photo", "Dosya uzantısı .jpg, .jpeg, .png ya da .gif olmalıdır.");

                    }
                }
                else
                {
                    // resim seçilip yüklenmese bile diğer bilgileri güncelle
                    galeryService.Update(galery);
                    return RedirectToAction("index");
                }


            }
           
            return View(galery);
        }
        public ActionResult Delete(Guid id)
        {
            galeryService.Delete(id);
            return RedirectToAction("Index");
        }
        public ActionResult Details(Guid id)
        {
            return View(galeryService.Find(id));
        }
    }
}

Blog.Admin/Controllers/PostController.cs
using Blog.Model;
using Blog.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Admin.Controllers
{
    public class PostController : ControllerBase
    {
        // GET: Post
        private readonly IPostService postService;
        private readonly ICategoryService categoryService;
        private readonly IPostFileService postFileService;
        public PostController(IPostService postService, ICategoryService categoryService, IPostFileService postFileService) :base()
        {
            this.postService = postService;
            this.categoryService = categoryService;
            this.postFileService = postFileService;
        }
        // GET: Post
        public ActionResult Index()
        {
            var post = postService.GetAll();
            return View(post);
        }
        public ActionResult Create()
        {
            var post = new Post();
            ViewBag.CategoryId = new SelectList(categoryService.GetAll(), "Id", "Name");
            return View(post);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Post post, HttpPostedFileBase[] Uploads)
        {
            if (ModelState.IsValid)
            {
                postService.Insert(post);
                if (Uploads != null && Uploads.Length >= 1)
                {
                    post.PostFiles.Clear();
                    foreach (var item in Uploads)
                    {
                        if (item != null && item.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(item.FileName);
                            var extension = Path.GetExtension(fileName).ToLower();
                            if (extension == ".jpg" || extension == ".gif" || extension == ".png" || extension == ".pdf" || extension == ".doc" || extension == ".docx"|| extension==".JPEG")
                            {
                                var path = Path.Combine(ConfigurationManager.AppSettings["uploadPath"], fileName);
                                item.SaveAs(path);
                                var file = new PostFile();
                                file.Id = Guid.NewGuid();
                                file.FileName = fileName;
                                file.CreatedAt = DateTime.Now;
                                file.CreatedBy = User.Identity.Name;
                                file.UpdatedAt = DateTime.Now;
                                file.UpdatedBy = User.Identity.Name;
                                file.PostId = post.Id;
                                postFileService.Insert(file);
                            }
                        }
                    }
                }
                
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(categoryService.GetAll(), "Id", "Name", post.CategoryId);
            return View(post);
        }
        public ActionResult Edit(Guid id)
        {
            var post = postService.Find(id);
            if (post == null)
            {
                return HttpNotFound();

            }
            ViewBag.CategoryId = new SelectList(categoryService.GetAll(), "Id", "Name", post.CategoryId);
            return View(post);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Post post, HttpPostedFileBase[] Uploads)
        {
            if (ModelState.IsValid)
            {

                var model = postService.Find(post.Id);
                if (Uploads != null && Uploads.Length >= 1)
                {
                    model.PostFiles.Clear();
                    foreach (var item in Uploads)
                    {
                        if (item != null && item.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(item.FileName);
                            var extension = Path.GetExtension(fileName).ToLower();
                            if (extension == ".jpg" || extension == ".gif" || extension == ".png" || extension == ".pdf" || extension == ".doc" || extension == ".docx")
                            {
                                var path = Path.Combine(ConfigurationManager.AppSettings["uploadPath"], fileName);
                                item.SaveAs(path);
                                var file = new PostFile();
                                file.Id = Guid.NewGuid();
                                file.FileName = fileName;
                                file.CreatedAt = DateTime.Now;
                                file.CreatedBy = User.Identity.Name;
                                file.UpdatedAt = DateTime.Now;
                                file.UpdatedBy = User.Identity.Name;
                                file.PostId = post.Id;
                                postFileService.Insert(file);
                            }
                        }
                    }
                }




                model.Title = post.Title;
                
                model.Description = post.Description;
               
               
                model.Photo = post.Photo;
                model.CategoryId = post.CategoryId;
                postService.Update(model);
            
                return RedirectToAction("Index");


            }
            ViewBag.CategoryId = new SelectList(categoryService.GetAll(), "Id", "Name", post.CategoryId);
            return View(post);
        }
        public ActionResult Delete(Guid id)
        {
            postService.Delete(id);
            return RedirectToAction("index");
        }

        public ActionResult Details(Guid id)
        {
            var post = postService.Find(id);
            if (post == null)
            {
                return HttpNotFound();

            }

            return View(post);
        }
    }
}

Blog.Admin/Views/Galery/Create.cshtml
@model Blog.Model.Galery
@{
    ViewBag.Title = "Create";
}

<h2>Yeni Fotoğraf</h2>

@using (Html.BeginForm("Create", "Galery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label for="Uploads" class="control-label col-md-2">
                Galeri Dosyaları
            </label>
            <div class="col-md-10">
                <input type="file" multiple name="Uploads" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye geri dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog.Admin/Views/Galery/Details.cshtml
@model Blog.Model.Galery

@{
                /**/

                ViewBag.Title = "Details";
}

<h2>Detay</h2>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd>
            <img src="@(ViewBag.AssetsUrl)@Model.Photo" style="width:300px;" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Listeye geri dön", "Index")
</p>

Blog.Admin/Views/Galery/Edit.cshtml
@model Blog.Model.Galery

@{
    ViewBag.Title = "Edit";
}

<h2>Düzenle</h2>


@using (Html.BeginForm("Edit", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <script src="https://cdn.ckeditor.com/4.11.2/standard/ckeditor.js"></script>
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Photo)
                @if (!string.IsNullOrEmpty(Model.Photo))
                {
                    <img src="@(ViewBag.AssetsUrl)@Model.Photo" style="width:300px;" /><br />
                }
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Listeye geri dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog.Admin/Views/Galery/Index.cshtml
@model IEnumerable<Blog.Model.Galery>

@{
    ViewBag.Title = "Index";
}

<h2>Galery</h2>

<p>
    <button type="button" class="btn btn-success"> @Html.ActionLink("Yeni Resim Ekle", "Create") </button>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>


            <td>
                <button type="button"> @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) </button>
                <button type="button">  @Html.ActionLink("DETAY", "Details", new { id = item.Id })  </button>
                <button type="button">   @Html.ActionLink("SİL", "Delete", new { id = item.Id })  </button>


            </td>
        </tr>
    }

</table>