Blog.Web/Models/Contacts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.Web.Models
{
    public class Contacts
    {
        [Display(Name = "Ad")]
        [Required(ErrorMessage = "{0} alanı gereklidir.")]
        [MaxLength(50, ErrorMessage = "{0} alanı en fazla {1} karakter uzunluğunda olabilir.")]
        public string FirstName { get; set; }
        [Display(Name = "Soyad")]
        [Required]
        [MaxLength(50)]
        public string LastName { get; set; }
        [Display(Name = "E-posta")]
        [Required]
        [EmailAddress]
        [MaxLength(100)]
        public string Email { get; set; }
        [Display(Name = "Telefon")]
        [Required]
        [Phone]
        [MaxLength(20)]
        public string Phone { get; set; }
    }
}

Blog.Web/Controllers/CategoryController.cs
using Blog.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IPostService postService;
        public CategoryController(ICategoryService categoryService, IPostService postService)
        {
            this.postService = postService;
            this.categoryService = categoryService;
        }
        // GET: Category
        public ActionResult Index()
        {
            ViewBag.Categories = categoryService.GetAll();
            ViewBag.AssetsUrl = ConfigurationManager.AppSettings["assetsUrl"];
            return View();
            
        }
        public ActionResult Details(Guid id)
        {
            var category = categoryService.Find(id);
            ViewBag.Categories = categoryService.GetAll();
            ViewBag.Posts = postService.GetAll();
            ViewBag.AssetsUrl = ConfigurationManager.AppSettings["assetsUrl"];
            return View(category);
        }
    }
}

Blog.Web/Controllers/GaleryController.cs
using Blog.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Web.Controllers
{
    public class GaleryController : Controller
    {
        private readonly IGaleryService galeryService;
        private readonly ICategoryService categoryService;
        public GaleryController(IGaleryService galeryService, ICategoryService categoryService)
        {
            this.categoryService = categoryService;
            this.galeryService = galeryService;
        }
        // GET: Galery
        public ActionResult Index()
        {
       
            ViewBag.AssetsUrl = ConfigurationManager.AppSettings["assetsUrl"];
            ViewBag.Categories = categoryService.GetAll();
            return View(galeryService.GetAll());
        }
    }
}

Blog.Web/Controllers/HomeController.cs
using Blog.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Blog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostService postService;
        private readonly ICategoryService categoryService;
        public HomeController(IPostService postService, ICategoryService categoryService)
        {
            this.postService = postService;
            this.categoryService = categoryService;
        }
        public ActionResult Index(int? page)
        {
           
            ViewBag.Categories = categoryService.GetAll();
            ViewBag.AssetsUrl = ConfigurationManager.AppSettings["assetsUrl"];
            var posts = postService.GetAll();
            var pageNumber = page ?? 1;
            var onePageOfPosts = posts.ToPagedList(pageNumber, 3);
            return View(onePageOfPosts);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            ViewBag.Categories = categoryService.GetAll();
            return View();
        }


        public ActionResult Contact()
        {
            ViewBag.Message = "İletişim sayfası.";
            ViewBag.Categories = categoryService.GetAll();
            return View();
        }

        [HttpPost]
        public ActionResult Contact(string firstName, string lastName, string email, string phone, string department, string message)
        {

            firstName = firstName.Trim();
            lastName = lastName.Trim();

            if (firstName == "")
            {

                ViewBag.Message = "Ad alanı gereklidir.";
                ViewBag.IsError = true;
                return View();
            }
            if (firstName.Length > 50)
            {
                ViewBag.Message = "Ad alanı 50 karakterden uzun olamaz";
                ViewBag.IsError = true;
                return View();
            }
            if (lastName == "")
            {

                ViewBag.Message = "Soyad alanı gereklidir";
                ViewBag.IsError = true;
                return View();
            }

            Regex regex = new Regex(@"^5(0[5-7]|[3-5]\d) ?\d{3} ?\d{4}$");//
            Match match = regex.Match(phone);
            if (match.Success == false)
            {
                ViewBag.Message = "Telefon 5XX XXX XXXX biçiminde olmalıdır.";
                ViewBag.IsError = true;
                return View();
            }

            //TODO Mail Gönderme İşlemi


            System.Net.Mail.MailMessage mailMessage = new System.Net.Mail.MailMessage();
            mailMessage.From = new System.Net.Mail.MailAddress("alifurkangokce@gmail.com", "ali");
            mailMessage.Subject = "İletişim Formu: " + firstName + " " + lastName;
            mailMessage.To.Add("alifurkangokce@gmail.com,alifurkangokce@gmail.com");
            string body;
            body = "Ad: " + firstName + "<br />";
            body = "Soyad: " + lastName + "<br />";
            body += "Telefon: " + phone + "<br />";
            body += "E-posta: " + email + "<br />";
            body += "Depart: " + department + "<br />";
            body += "Mesaj: " + message + "<br />";
            mailMessage.IsBodyHtml = true;
            mailMessage.Body = body;


            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential("mail", "şifre");
            smtp.EnableSsl = true;
            smtp.Send(mailMessage);

            ViewBag.Message = "Mesajınız gönderildi. Teşekkür ederiz.";
            //TODO: Mail Gönderme işlemi yapılacak.
            ViewBag.Message = "Form başarıyla iletildi,en kısa zamanda dönüş yapacağız.";
            return View();
        }
    }
}

Blog.Web/Controllers/PostController.cs
using Blog.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPortfolio.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService postService;
        private readonly ICategoryService categoryService;

        public PostController(IPostService postService, ICategoryService categoryService)
        {
            this.postService = postService;
            this.categoryService = categoryService;

        }
        // GET: Post
        public ActionResult Index()
        {

           // ViewBag.Categories = categoryService.GetAll();
            //int skip = (page - 1) * 5;
            //int take = 5;
            //int pageCount = Convert.ToInt32((Math.Ceiling((double)postService.GetAll().OrderByDescending(o => o.CreatedAt).Count() / (double)5)));
            //ViewBag.PageCount = pageCount;
            //// sayfa noya göre 5 kayıt getir
            //var posts = postService.GetAll().OrderByDescending(o => o.CreatedAt).Skip(skip).Take(take).ToList();

            // son yazılar

            //ViewBag.Page = page;
            ViewBag.AssetsUrl = ConfigurationManager.AppSettings["assetsUrl"];
            return View();
        }
        public ActionResult Details(Guid id)
        {
            ViewBag.Categories = categoryService.GetAll();
            var post = postService.Find(id);
            ViewBag.AssetsUrl = ConfigurationManager.AppSettings["assetsUrl"];
            return View(post);
        }

        public ActionResult RecentPosts()
        {
            ViewBag.RecentPosts = postService.GetAll().OrderByDescending(o => o.CreatedAt).Take(4).ToList();
            return PartialView();
        }
    }
}

Blog.Web/Views/Category/Details.cshtml
@model Blog.Model.Category

<section class="s-pageheader s-pageheader--home">

    <header class="header">
        <div class="header__content row">

            <div class="header__logo">
                <a class="logo" href="@Url.Action("Index", "Home")">
                    <img src="/images/BLG.jpg" alt="Homepage">
                </a>
            </div> <!-- end header__logo -->

            <ul class="header__social">
                <li>
                    <a href="http://www.facebook.com"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.twitter.com"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.instagram.com"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.pinterest.com"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                </li>
            </ul> <!-- end header__social -->

            


            <a class="header__toggle-menu" href="/#0" title="Menu"><span>Menu</span></a>

            <nav class="header__nav-wrap">

                <h2 class="header__nav-heading h6">Site Navigation</h2>

                <ul class="header__nav">
                    <li class="current"><a href="@Url.Action("Index", "Home")">Anasayfa</a></li>
                    <li class="has-children">
                        <a href=>Kategoriler</a>
                        <ul class="sub-menu">

                            @foreach (var item in ViewBag.Categories)
                            {
                                <li>
                                    <a href="@Url.Action("Details","Category",new { id = item.Id })">@item.Name</a>
                                </li>
                            }
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Galery")">Galeri</a>
                    </li>
                    <li><a href="@Url.Action("About", "Home")">Hakkında</a></li>
                    <li><a href="@Url.Action("contact", "Home")">İletişim</a></li>
                </ul> <!-- end header__nav -->

                <a href="/#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

            </nav> <!-- end header__nav-wrap -->

        </div> <!-- header-content -->
    </header> <!-- header -->


    <div class="pageheader-content row">
        <div class="col-full">

            <div class="featured">

                <div class="featured__column featured__column--big">

                    <div class="entry">
                        <video width="750" controls>
                            <source src="~/Videos/1.mp4" type="video/mp4">

                        </video>

                    </div> <!-- end entry -->
                </div> <!-- end featured__big -->

                <div class="featured__column featured__column--small">

                    <div class="entry" style="background-image:url('images/thumbs/featured/featured-watch.jpg');">

                        <div class="entry__content">
                            <span class="entry__category"><a href="/#0">GELECEĞİN TEKNOLOJİLERİ</a></span>

                            <h1><a href="/#0" title="">Zaman yönetimi ve sağlık doğru orantılıdır.</a></h1>

                        </div> <!-- end entry__content -->

                    </div> <!-- end entry -->

                    <div class="entry" style="background-image:url('images/thumbs/featured/featured-beetle.jpg');">

                        <div class="entry__content">
                            <span class="entry__category"><a href="/#0">SAĞLIKLI YAŞAM</a></span>

                            <h1><a href="/#0" title="">Sınırlaını sporla keşfet</a></h1>

                        </div> <!-- end entry__content -->

                    </div> <!-- end entry -->

                </div> <!-- end featured__small -->
            </div> <!-- end featured -->

        </div> <!-- end col-full -->
    </div> <!-- end pageheader-content row -->

</section> <!-- end s-pageheader -->
<section class="s-content">

    <div class="row narrow">
        <div class="col-full s-content__header" data-aos="fade-up">
            <h1>@Model.Name</h1>

            <div class="s-content__media col-full">
                <div class="s-content__slider slider">
                    <div class="slider__slides">
                        @foreach (var item in Model.CategoryFiles)
                        {
                            <div class="slider__slide">
                                <img src="@(ViewBag.AssetsUrl)@(item.FileName)" style=" width:100%;" />
                            </div>

                        }
                    </div>
                </div>
            </div> <!-- end s-content__media -->


        </div>
    </div>
    <div class="row">
        <div class="masonry-wrap">
            <div class="masonry">
                @foreach (var item in Model.Posts)
                {
                    <div class="col-md-4">
                        <div class="entry__text">
                            <div class="entry__header"style="background-color:#e6e8ed">
                                @*<a class="entry__header" href="@Url.Action("Details", "Category", new { id = item.Id })"><h3>@item.Title</h3></a>*@
                                <p class="entry__header" style="font-size:40px;color:black;font-family:'Times New Roman' !important; font-weight:bold">@Html.Raw(item.Title)</p>
                            </div>
                        </div>

                        <div class="entry__text">
                            <div class="entry__thumb">

                                <p>@Html.Raw(item.Description)</p>


                            </div>
                        </div>
                    </div>

                }
            </div>
        </div>

    </div>


    

</section> <!-- s-content -->
<!-- s-extra
================================================== -->
<section class="s-extra">

    <div class="row top">

         <!-- end popular -->

         <!-- end about -->

    </div> <!-- end row -->

     <!-- end tags-wrap -->

</section> <!-- end s-extra -->

Blog.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="s-pageheader">

    <header class="header">
        <div class="header__content row">

            <div class="header__logo">
                <a class="logo" href="@Url.Action("Index", "Home")">
                    <img src="/images/BLG.jpg" alt="Homepage">
                </a>
            </div> <!-- end header__logo -->

            <ul class="header__social">
                <li>
                    <a href="http://www.facebook.com"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.twitter.com"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.instagram.com"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.pinterest.com"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                </li>
            </ul> <!-- end header__social -->

           


            <a class="header__toggle-menu" href="/#0" title="Menu"><span>Menu</span></a>

            <nav class="header__nav-wrap">

                <h2 class="header__nav-heading h6">Site Navigation</h2>

                <ul class="header__nav">
                    <li class="current"><a href="@Url.Action("Index", "Home")">Anasayfa</a></li>
                    <li class="has-children">
                        <a href=>Kategoriler</a>
                        <ul class="sub-menu">

                            @foreach (var item in ViewBag.Categories)
                            {
                                <li>
                                    <a href="@Url.Action("Details","Category",new { id = item.Id })">@item.Name</a>
                                </li>
                            }
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Galery")">Galeri</a>
                    </li>
                    <li><a href="@Url.Action("About", "Home")">Hakkında</a></li>
                    <li><a href="@Url.Action("contact", "Home")">İletişim</a></li>
                </ul> <!-- end header__nav -->

                <a href="/#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

            </nav> <!-- end header__nav-wrap -->

        </div> <!-- header-content -->
    </header> <!-- header -->

</div> <!-- end s-pageheader -->
<section class="s-content s-content--narrow">

    <div class="row">

        <div class="s-content__header col-full">
            <h1 class="s-content__header-title">
                Hakkımızda
            </h1>
        </div> <!-- end s-content__header -->

        <div class="s-content__media col-full">
            <div class="s-content__post-thumb">
                <img src="images/thumbs/about/about-1000.jpg"
                     srcset="images/thumbs/about/about-2000.jpg 2000w,
                                 images/thumbs/about/about-1000.jpg 1000w,
                                 images/thumbs/about/about-500.jpg 500w"
                     sizes="(max-width: 2000px) 100vw, 2000px" alt="">
            </div>
        </div> <!-- end s-content__media -->

        <div class="col-full s-content__main">

            <p class="lead">Blog safamızın amacı biz kimiz, neler yaptık, neler yapmak istiyoruz. Bizi daha iyi tanımanız için.. </p>

            <p>
                Blog sayfamızın backend ve front end kısmında gerekli işlerin tamamlanmasını sağlayan Ali Fukan Gökçe'ir. Ali Furkan Gökçe 24 yaşındadır. Lisans hayatını İstanbul sabahattin zaim üniversitesi - Bilgisayar mühendisliği bölümünde tamamlamıştır. Profesyonel iş hayatına atılmadan önce işkur nitelikli bilişim uzmanı yetiştirme programına katılıp kendini yazılım konusunda geliştirmek istemiştir. İş hayatına front end developer olarak başlayıp kendini bu konuda uzmanlaştırmak istemektedir. Ali mesleği için araşırma yaptığı zamanların dışında spora çok vakit ayırır. Vücut gelişirme Ali'nin hem rahatlama hem kendini dinleme biçimidir. Ayrıca sıkı bir voleybol oyuncusudur. Su sporlarıyla ilgilidir. Satranç oynamayı zihninin geliştirdiğini savunur ve bunu bir iş gibi görür. Ali müzikle de ilgilidir ve bağlama çalar. Amatör olarak yaptığı bu hobi onu rahatlatmasının yanında arkadaşlarını eğlendimeyi de hedefler. Müze gezmek de Ali'nin sevdiği akiviteler arasındadır. Sitemizin tasarımında yardımcı ve içerikleri hazırlayan Onur Altınkaya 26 yaşındadır. Beykent üniversitesi - Matematik/Bilgisayar bölümünü bitirmiştir. Onur üniversite hayatını bitirdikten sonra yazılımda kendini geliştirmek için java eğitimi almışır. Daha sonra o da  işkur nitelikli bilişim uzmanı yetiştirme programına katılıp C# ve .NET eğitimi almıştır. Ali ve Onur bu kurs sayesinde tanıştı. Onur yazılımla ilgili aldığı eğitimler ve araştırmalar sonucunda iş hayatına tester olarak başlayıp, test uzmanı ve test mühendisliğine yükselmek istemektedir. Onur eğitim hayatı dışında kalan zamanlarda spor ve müziğe çok zaman ayırır. 5 yıldır vücut geliştime ile ilgilenmektedir. Lise hayatında lisanslı olarak basketbol oynamıştır ve yüzmeyi çok sever. Farklı tarzda müzik türlerini takip etiken sonra sıkı bir elektronik müzik takipçisi olmuştur. Bununla ilgili araştırmalar yapar kullanabildiği klavye, saksafon ve programlar sayesinde müzik üretmekte ister. 
            </p>

           

            <div class="row block-1-2 block-tab-full">
          

                <div class="col-block">
                    <h3 class="quarter-top-margin">Misyonumuz</h3>
                    <p>İş hayatında başlayıp devam etmek istediğimiz alanlarda işimizin en iyilerinden olmak misyonumuzdur. Farklı freelance projelerde bir araya gelip birbirimizi geliştirmede yardımcı olmak ve ilgi alanlarımızla yaptığımız işi harmanlayıp ortaya güzel işler çıkarmak da en önemli misyonumuzdur.</p>
                </div>

              
            </div>


        </div> <!-- end s-content__main -->

    </div> <!-- end row -->

</section> <!-- s-content -->
<!-- s-extra
================================================== -->
 <!-- end s-extra -->

Blog.Web/Views/Home/Contact.cshtml
@model Blog.Web.Models.Contacts
@{
    ViewBag.Title = "Contact";

}
<div class="s-pageheader">

    <header class="header">
        <div class="header__content row">

            <div class="header__logo">
                <a class="logo" href="@Url.Action("Index", "Home")">
                    <img src="/images/BLG.jpg" alt="Homepage">
                </a>
            </div> <!-- end header__logo -->

            <ul class="header__social">
                <li>
                    <a href="http://www.facebook.com"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.twitter.com"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.instagram.com"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                </li>
                <li>
                    <a href="http://www.pinterest.com"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                </li>
            </ul> <!-- end header__social -->

            


            <a class="header__toggle-menu" href="/#0" title="Menu"><span>Menu</span></a>

            <nav class="header__nav-wrap">

                <h2 class="header__nav-heading h6">Site Navigation</h2>

                <ul class="header__nav">
                    <li class="current"><a href="@Url.Action("Index", "Home")">Anasayfa</a></li>
                    <li class="has-children">
                        <a href="">Kategoriler</a>
                        <ul class="sub-menu">

                            @foreach (var item in ViewBag.Categories)
                            {
                                <li>
                                    <a href="@Url.Action("Details","Category",new { id = item.Id })">@item.Name</a>
                                </li>
                            }
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Galery")">Galeri</a>
                    </li>
                    <li><a href="@Url.Action("About", "Home")">Hakkında</a></li>
                    <li><a href="@Url.Action("contact", "Home")">İletişim</a></li>
                </ul> <!-- end header__nav -->

                <a href="/#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

            </nav> <!-- end header__nav-wrap -->

        </div> <!-- header-content -->
    </header> <!-- header -->

</div> <!-- end s-pageheader -->
<!-- s-content
================================================== -->
<section class="s-content s-content--narrow">

    <div class="row">

        <div class="s-content__header col-full">
            <h1 class="s-content__header-title">
                Bize ulaşın
            </h1>
        </div> <!-- end s-content__header -->

        <div class="s-content__media col-full">
            <div class="mapouter"><div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=wissen&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.jetzt-drucken-lassen.de">jetzt-drucken-lassen.de</a></div>
            <style>
                .mapouter {
                    text-align: right;
                    height: 500px;
                    width: 600px;
                }

                .gmap_canvas {
                    overflow: hidden;
                    background: none !important;
                    height: 500px;
                    width: 600px;
                }
            </style></div>
        </div> <!-- end s-content__media -->

        <div class="col-full s-content__main">

            <p class="lead">Tavsiyelerniz ve şikayeleriniz bizim için çok önemlidir. Ayrıca iş teklifleri için bize ulaşabileceğiniz bazı bilgiler aşağıdadır.</p>

            <div class="row">
                <div class="col-six tab-full">
                    <h3>Bizi nerede bulabilirsiniz?</h3>

                    <p>
                        Barbaros bulvarı, Yıldız iş hanı<br>
                        No:9/3 Beşiktaş-İstanbul<br>
                        34353
                    </p>

                </div>

                <div class="col-six tab-full">
                    <h3>İletişim Bilgileri</h3>

                    <p>
                        onuralinkayaa@gmail.com<br>
                        alifurkangokce@gmail.com<br>
                        Phone: (+1) 123 456
                    </p>

                </div>
            </div> <!-- end row -->

            <h3>Merhaba</h3>
            <div class="col-lg-12">
                @if (ViewBag.Message != null)
                {
                    <div class="alert alert-danger">@ViewBag.Message</div>
                }
                @using (Html.BeginForm())
                {
                    <div class="row">
                        <div class="form-horizontal col-lg-6">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.ValidationMessage("Error", new { @class = "text-danger" })

                            <div class="form-group">

                                @Html.LabelFor(modelItem => modelItem.FirstName, new { @class = "control-label col-md-6" })

                                <div class="col-lg-12">
                                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(modelItem => modelItem.LastName, new { @class = "control-label col-md-6" })
                                <div class="col-lg-12">
                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>

                            </div>
                        </div>
                        <div class="form-horizontal col-lg-6">
                            <div class="form-group">
                                @Html.LabelFor(modelItem => modelItem.Email, new { @class = "control-label col-md-6" })
                                <div class="col-lg-12">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(modelItem => modelItem.Phone, new { @class = "control-label col-md-6" })
                                <div class="col-lg-12">
                                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-horizontal col-md-12">
                            <div class="col-md-12">
                                <label>Mesajınız <span class="required">*</span></label>
                                <textarea rows="2" id="message_contact" class="form-control" name="Mesajınız" style="margin-left:0px;margin-right:0px; width:631px;"></textarea>
                            </div>
                        </div>
                    </div>


                    <br />
                    <div class="form-group">
                        <div class="col-lg-12 col-md-offset-2" style="float:right">
                            <input type="submit" class="btn btn-primary" value="Gönder" />
                        </div>
                    </div>


                }
            </div>

            <!-- end form -->


        </div> <!-- end s-content__main -->

    </div> <!-- end row -->

</section> <!-- s-content -->
<!-- s-extra
================================================== -->
 <!-- end s-extra -->